#!/bin/bash
# #########################################################################
#   Build Script for BNGParser
# #########################################################################
echo ' '
echo ' '
echo ' '
echo ' This script should be called right after cloning the GitHub code.'
echo ' Building the parser before importing the code into Eclipse will'
echo ' ensure that Eclipse is using the right parser.'
echo ' '

#/bin/rm -r -f  BNGParser
#git clone https://github.com/RuleWorld/BNGParser.git
cd src/bngparser/grammars

echo '-------------------------------------------------------------------'
echo ' Generate grammars'
echo '-------------------------------------------------------------------'

java -jar  ../../antlr-3.3-complete.jar BNGLexer.g
# ASS2019 - This thing DOES NOT compile with Java 8 or above so you will need
# JDK1.7 or under. I'm using openJDK here and will leave this here as a reminder 
# I normally wouldn't hard code anything but this NEEDS to be fixed if you want to 
# actually compile this. Alternative and better solution is to upgrade to 
# ANTLR 3.5.2 but this source code doesn't compile with that either.
~/apps/open_jdk7/bin/java -jar  ../../antlr-3.3-complete.jar BNGGrammar.g

echo '-------------------------------------------------------------------'
echo ' Compile grammars'
echo '-------------------------------------------------------------------'

cd ../..
for jfile in $(ls bngparser/grammars/*.java)
do
echo $jfile
javac    -classpath  bngparser/grammars:bngparser/methods:bngparser/models:bngparser/dataType:bngparser/exceptions:antlr-3.3-complete.jar:../commons-lang3-3.1.jar:.  -sourcepath . $jfile
done

echo '-------------------------------------------------------------------'
echo ' Compiling methods '
echo '-------------------------------------------------------------------'

for jfile in $(ls bngparser/methods/*.java)
do
  echo $jfile
javac    -classpath  bngparser/grammars:bngparser/methods:bngparser/models:bngparser/dataType:bngparser/exceptions:antlr-3.3-complete.jar:../commons-lang3-3.1.jar:.  -sourcepath . $jfile
done

echo '-------------------------------------------------------------------'
echo ' Compiling dataType '
echo '-------------------------------------------------------------------'

for jfile in $(ls bngparser/dataType/*.java)
do
  echo $jfile
javac    -classpath  bngparser/grammars:bngparser/methods:bngparser/models:bngparser/dataType:bngparser/exceptions:antlr-3.3-complete.jar:../commons-lang3-3.1.jar:.  -sourcepath . $jfile
done

echo '-------------------------------------------------------------------'
echo ' Compiling exceptions '
echo '-------------------------------------------------------------------'

for jfile in $(ls bngparser/exceptions/*.java)
do
  echo $jfile
javac    -classpath  bngparser/grammars:bngparser/methods:bngparser/models:bngparser/dataType:bngparser/exceptions:antlr-3.3-complete.jar:../commons-lang3-3.1.jar:.  -sourcepath . $jfile
done

echo '-------------------------------------------------------------------'
echo ' Compiling bngparser '
echo '-------------------------------------------------------------------'

for jfile in $(ls bngparser/*.java)
do
  if [ $jfile != 'bngparser/MCellTranslatorTester.java' ];
then
  if [ $jfile != 'bngparser/Tester.java' ];
then
echo $jfile
javac    -classpath  bngparser/grammars:bngparser/methods:bngparser/models:bngparser/dataType:bngparser/exceptions:antlr-3.3-complete.jar:../commons-lang3-3.1.jar:.  -sourcepath . $jfile
fi
fi
done

echo '-------------------------------------------------------------------'
echo ' Creating jar '
echo '-------------------------------------------------------------------'

cp ../xml.stg .
jar cf  BNGParser.jar bngparser  xml.stg

echo '-------------------------------------------------------------------'
echo ' Running tests '
echo '-------------------------------------------------------------------'

cp ../commons-lang3-3.1.jar .

javac -cp antlr-3.3-complete.jar:BNGParser.jar:commons-lang3-3.1.jar:. \
    bngparser/Tester.java 
java  -cp antlr-3.3-complete.jar:BNGParser.jar:commons-lang3-3.1.jar:. \
    bngparser/Tester

echo '-------------------------------------------------------------------'
echo ' Done '
echo '-------------------------------------------------------------------'
